<a href="https://colab.research.google.com/github/sameermdanwer/python-assignment-/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of the variables list_ and array_list.

list_ is a Python list.
array_list is a NumPy array.
To print the data types of both variables, you can use the following code:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

To print the data type of each element in both list_ and array_list, you can use Python's built-in type() function for the list_ elements and NumPy's dtype attribute for array_list. Here's the code:



In [3]:
import numpy as np

# Original list
list_ = ['1', '2', '3', '4', '5']
# Convert to NumPy array
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Yes, there will be a difference in the data type of the elements in list_ and array_list after setting dtype=int for the array_list. The list_ will still contain elements of type str (as it is a list of strings), while array_list will convert those string elements into integers (type int).

Here is the updated code that prints the data type of each element in both list_ and array_list:

In [4]:
import numpy as np

# Original list
list_ = ['1', '2', '3', '4', '5']

# Convert to NumPy array with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
import numpy as np

# Original list of lists
num_list = [[1, 2, 3], [4, 5, 6]]

# Convert to NumPy array
num_array = np.array(object=num_list)

# Finding the shape and size of num_array
shape_of_array = num_array.shape
size_of_array = num_array.size

# Print the results
print(f"Shape of num_array: {shape_of_array}")
print(f"Size of num_array: {size_of_array}")

Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [6]:
import numpy as np

# Create a 3x3 NumPy array of zeros
zero_matrix = np.zeros((3, 3))

# Print the matrix
print("3x3 matrix of zeros:")
print(zero_matrix)

3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

To create an identity matrix of shape (5,5) using NumPy, you can use the np.identity() or np.eye() function. Both are designed to generate identity matrices, but np.eye() allows more flexibility with diagonal offsets.

In [7]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
